# This is a basic workflow to help you get started with Actions

name: Build and Release

# Controls when the workflow will run
on:
  push:
    branches: ['workplace']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
